(write (mem-allocated))
(include "src/fib.scm")
(define gc-stat (lambda ()
                  (write "Memory before/after gc:")
                  (write (mem-allocated))
                  (gc)
                  (write (mem-allocated))))
(define + 134)
(gc-stat)
(write (fib 20))
(gc-stat)
(include "src/subtest.scm")
(include "src/subtest.scm")
(gc-stat)
(write +)

