(write (mem-allocated))
(write (mem-occupied))
(include "src/fib.scm")
(define gc-stat (lambda ()
                  (write "Memory before/after gc:")
                  (write (mem-allocated))
                  (gc)
                  (write (mem-allocated))))
(define reverse 134)
(define newvar 57)
(write (mem-occupied))
(gc-stat)
(write (mem-occupied))
(write (fib 20))
(write (mem-occupied))
(gc-stat)
(write (mem-occupied))
(include "src/subtest.scm")
(include "src/subtest.scm")
(gc-stat)
(write reverse)
(write newvar)
(write (mem-occupied))

