(include "src/fib.scm")
(define gc-stat (lambda ()
                  (write "Memory before/after gc:")
                  (write (mem-allocated))
                  (gc)
                  (write (mem-allocated))))
(write (quote (fib 32)))
(write (fib 32))
(write "mem-gc-times")
(write (mem-gc-times))
(write "mem-max-allocated")
(write (mem-max-allocated))

